fname: 'fomm_att1_att2_mm_fold3' # name of the run; will save in tb_logs/test_fomm
parameters:   
  model_name: ['fomm_att']
  dataset: ['mm']
  fold: [3]
  # dim_stochastic: [48] 
  dim_hidden: [300]
  # etype: ['lin']
  # ttype: ['gated']
  mtype: ['attn_transition']
  bs: [600]
  C: [0.01] 
  reg_all: [True] 
  reg_type: ['l1'] 
  alpha1_type: ['linear']
  otype: ['identity']
  checkpoint_callback: [False] # switch to True if you want to save best model
  logger: [False]
  check_val_every_n_epoch: [10]
  max_epochs: [10000]
  progress_bar_refresh_rate: [1]
  gpu_id: [2]
  add_stochastic: [True]
  att_mask: [True]
  optuna: [True]
  num_optuna_trials: [10]
 