fname: 'fomm_lin_semi_synthetic_indist_sc_missing_alt' # name of the run; will save in tb_logs/test_fomm
parameters:   
  model_name: ['fomm']
  dataset: ['semi_synthetic']
  fold: [1]
  seed: [0]
  nsamples_syn: [1000,1500,2000,10000] #50,1000 
  dim_hidden: [300]
  mtype: ['linear']
  bs: [600]
  C: [0.01]
  reg_all: [True]
  reg_type: ['l1']
  alpha1_type: ['linear']
  otype: ['linear']
  checkpoint_callback: [False] # switch to True if you want to save best model
  logger: [False]
  check_val_every_n_epoch: [10]
  max_epochs: [5000]
  progress_bar_refresh_rate: [1]
  gpu_id: [0]
  add_stochastic: [False]
  ss_missing: [True]
  ss_in_sample_dist: [True]
  optuna: [True]