fname: 'rnn_pkpd_semi_synthetic_indist_sc_missing_alt' # name of the run; will save in tb_logs/test_fomm
parameters:   
  model_name: ['gru']
  dataset: ['semi_synthetic']
  fold: [1]
  seed: [0]
  nsamples_syn: [1000,1500,2000,10000]
  dim_hidden: [500]
  mtype: ['pkpd_gru']
  bs: [600]
  C: [0.01]
  reg_all: [False]
  reg_type: ['l2']
  alpha1_type: ['linear']
  otype: ['linear']
  checkpoint_callback: [False] # switch to True if you want to save best model
  logger: [False]
  check_val_every_n_epoch: [10]
  max_epochs: [500]
  progress_bar_refresh_rate: [1]
  gpu_id: [3]
  add_stochastic: [False]
  ss_missing: [True]
  ss_in_sample_dist: [True]
  optuna: [True]